**Name:** Shardul Narvekar

**Roll No.:** UAI05BT223414

**Division:** B

**Subject:** Deep Learning


In [1]:
# Q9.c) Implementing NOR gate, using a single perceptron

First understand the input data

x1 x2 y
0  0  1
0  1  0
1  0  0
1  1  0

We will represent this in the form of matrix - Rank 2 Tensor
Thus we will use the numpy library

In [2]:
import numpy as np
#we import the required library

In [3]:
input_data=np.array([[0,0],[0,1],[1,0],[1,1]])
#matrix representation

In [4]:
input_data

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
input_data.ndim #its rank

2

In [6]:
input_data.shape

(4, 2)

In [7]:
output_data=np.array([1,0,0,0]) #save the output data

In [8]:
output_data

array([1, 0, 0, 0])

In [9]:
output_data.ndim

1

In [10]:
output_data.shape

(4,)

In [11]:
#now we have to define, what are the additional parameters which are required

z=x1*w1+x2*w2+b

In [12]:
#we randomly initialize the weight, e.g. for the 1st epoch, we initialize as 0

In [13]:
#we can define it individually, but going ahead its not a good practice

w=[w1,w2]

In [14]:
#thus we do like above

In [15]:
weights=np.zeros(2)

In [16]:
weights

array([0., 0.])

In [17]:
#above is a method to assign the weights as zero

In [18]:
weights.ndim

1

In [19]:
weights.shape

(2,)

In [20]:
#bias is a scalar quantity

In [21]:
bias = 0

In [22]:
#the no.of times the perceptron will have a look at the entire dataset is called an epoch

In [23]:
epoch=10

In [24]:
#Learning Rate (eta)

In [25]:
eta=0.1

In [26]:
#now we define the activation function

In [27]:
def activation(z):
    if z>0:
        return 1
    else:
        return 0

In [28]:
len(input_data)

4

In [29]:
for i in range (epoch):
    print(f'Epoch:{i}')
    for j in range(len(input_data)):
        print(input_data[j])

Epoch:0
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:1
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:2
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:3
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:4
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:5
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:6
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:7
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:8
[0 0]
[0 1]
[1 0]
[1 1]
Epoch:9
[0 0]
[0 1]
[1 0]
[1 1]


In [30]:
for i in range (epoch):
    print(f'Epoch:{i}')
    print()
    for j in range(len(input_data)):
        x=input_data[j]
        yactual=output_data[j]
        z=np.dot(x,weights)+bias
        ypred = activation(z)
        error=yactual-ypred
        # print(error)
        #there is an error in the for iteration, thus we update the weight
        #refer the notebook
        weights=weights+(eta*error*x)
        bias=bias+eta*error
        #above is the formula to update the bias
        #note: the weights are getting updated after the 1st Epoch

        print("Actual Value: ",yactual)
        print("Predicted Value: ",ypred)
        print("Error: ",error)
        print()
    print()
    print()

Epoch:0

Actual Value:  1
Predicted Value:  0
Error:  1

Actual Value:  0
Predicted Value:  1
Error:  -1

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0



Epoch:1

Actual Value:  1
Predicted Value:  0
Error:  1

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  1
Error:  -1

Actual Value:  0
Predicted Value:  0
Error:  0



Epoch:2

Actual Value:  1
Predicted Value:  0
Error:  1

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0



Epoch:3

Actual Value:  1
Predicted Value:  1
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0



Epoch:4

Actual Value:  1
Predicted Value:  1
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:  0
Error:  0

Actual Value:  0
Predicted Value:

In [31]:
weights

array([-0.1, -0.1])

In [32]:
print(bias)

0.1
